[[language]]
name = "python"
roots = [
  "main.py",
  "requirements.txt",
]
language-server = { command = "pyright-setup" }
# language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
indent = { tab-width = 2, unit = "  " }
config = {}